version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: astroid
    versions:
    - 2.4.2
    - "2.5"
    - 2.5.1
    - 2.5.2
    - 2.5.3
  - dependency-name: pylint
    versions:
    - 2.6.0
    - 2.6.2
    - 2.7.0
    - 2.7.1
    - 2.7.2
    - 2.7.3
    - 2.7.4
  - dependency-name: soupsieve
    versions:
    - "2.1"
    - "2.2"
  - dependency-name: lazy-object-proxy
    versions:
    - 1.5.2
